language: php

php:
  - 5.6
  - 7.0
  - hhvm

services:
  - redis-server

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpunit
